test(`sum`, () => {
// if there is no error then test is passed
})

test(`sum`, () => {
    throw new Error('Failure')
    // and if there is error then test case is fail
}) 

// 
// why tests
// 
//  - Save time
//  - Create reliable software
//  - Gives flexibility to devlopers
//      - Refactoring
//      - Collaborating
//      - Profiling
//  - Peace of mind